### ISSUE TITLE
Move some of the folders in "assets/" to something like "src/"

### ISSUE THREAD

**Issue by diced** [Katrixerse/Corius#13]
**Is your feature request related to a problem? Please describe.**
Yes, generally the `assets/` folder is tied to pictures and other static things, they shouldn't really have code in them.

**Describe the solution you'd like**
Although there are some folders inside of `assets/` that should be there, they can stay, but folders like `assets/handlers` and `assets/exports` should be moved to `src/handlers` and `src/exports`

**Comment by wzhouwzhou** [comment]
+348

**Comment by kdev** [comment]
If you do this, you should
1. move every `.js` file into the `src/` folder
2. put all the files in `assets/` into smth like `utils/`

**Comment by Katrixerse** [comment]
This has been changed in  [45ad131c1627ed70bc134feaaf5033a54d35ce32](https://github.com/Katrixerse/Corius/commit/45ad131c1627ed70bc134feaaf5033a54d35ce32)
