### ISSUE TITLE
[SECURITY] Vulnarable to SQL-Injections

### ISSUE THREAD

**Issue by kdev** [Katrixerse/Corius#15]
**Describe the vulnerability**
Your code is vulnarable to SQL injections since you are not escaping values when executing queries

**How to fix**
Use `mysql.escape()` when inserting a value into a select query or something like `mysql.format()` to format your query before sending.

**Additional context**
I found some spots [here](https://github.com/Katrixerse/Corius/blob/master/commands/miscellaneous/bugs.js#L2) and in many of the other [moderation](https://github.com/Katrixerse/Corius/blob/master/commands/moderation) commands

**Comment by Katrixerse** [comment]
Hopefully Fixed this issue with [7865f79dc](https://github.com/Katrixerse/Corius/commit/7865f79dcf03f7619b3cebee1845331bd1687460)
[11389fea](https://github.com/Katrixerse/Corius/commit/11389fea171c504eb04c4434517b681f4ca5cb47)
[b8f99ec8e](https://github.com/Katrixerse/Corius/commit/b8f99ec8e4667d6282451c1e1bcb8ef12aa75741)
