### ISSUE TITLE
Change code from v11 to v12 

### ISSUE THREAD

**Issue by thsanki** [Katrixerse/Corius#8]
Because after October v11 code bot is not going to work ..
So please convert it into v12 code i am waiting for v12 code😎😎😎

**Comment by Wolfkid200444** [comment]
Maybe u should updated yourself i donnut

**Comment by thsanki** [comment]
> Maybe u should updated yourself i donnut

Can u give your DISCORD server link or discord id where i come and talk to u ?

**Comment by Wolfkid200444** [comment]
sure

**Comment by Wolfkid200444** [comment]
https://discord.gg/ZU8zFx8
